module.exports = env => {
  // TODO!!: real production build (minify)
  env = env || {} // undefined if webpack called without `--env`
  return {
    entry: './src/index.js',
    output: {
      filename: 'bundle.js',
      path: __dirname + '/dist',
    },
    module: {
      rules: [
        {
          test: /\.rs$/,
          use: {
            loader: 'rust-wasm-loader',
            options: {
              // The path to the webpack output relative to the project root
              path: '',
              // release: env.production,
            }
          }
        }
      ]
    },
    // The .wasm 'glue' code generated by Emscripten requires these node builtins,
    // but won't actually use them in a web environment. We tell Webpack to not resolve those
    // require statements since we know we won't need them.
    externals: {
      'fs': true,
      'path': true,
    },

    devServer: {
      contentBase: __dirname + "/dist/",
      overlay: true,    // shows Rust compiler errors in the browser
      open: true,       // opens http://localhost:8080 in browser
      compress: false,  // gzip compression
    }
  }
}
